### ISSUE TITLE
Choose Names

### ISSUE THREAD

**Issue by ryayak1460** [ryayak1460/5th#3]
Players can choose names for their characters.  Some races have more than one name associated with them.

Request:
```javascript
{
  character, // object
  names // object, keys are name types, values are the names
}
```

Response:
```javascript
{
  character: {
    names: {} // object,  keys are name types, values are the names
  }
}
```

**Estimate**: 6h
**Actual**:
**Tasks**:
- Dwarf
    - [x] Given Name
    - [x] Clan Name
- Elf
    - [x] Child Name
    - [x] Adult Name
    - [x] Family Name
- Halfling
    - [x] Given Name
    - [x] Family Name
    - [x] Nickname
- Human
    - [x] Given Name
    - [x] Surname
- Dragonborn
    - [x] Childhood Name
    - [x] Given Name
    - [x] Clan Name
- Gnome
    - [x] Given Name 1 (mother)
    - [x] Given Name 2 (father)
    - [x] Given Name 3 (clan elder)
    - [x] Given Name 4 (aunt)
    - [x] Clan Name
    - [x] Nickname
- Half-Elf (raised among humans)
    - [x] Child Name
    - [x] Adult Name
    - [x] Family Name
- Half-Elf (raised among elfs)
    - [x] Given Name
    - [x] Surname
- Half-Orc (human)
    - [x] Given Name
    - [x] Surname
- Half-Orc (orc)
    - [x] Orc Name
- Tiefling (human)
    - [x] Given Name
- Tiefling (heritage)
    - [x] Infernal Name
- Tiefling (chosen)
    - [x] Virtue Name
